package com.ey.poc.entity;


import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

/**
 * RmtSubServiceline generated by hbm2java
 */
@Entity
@Table(name="RMT_INTW_LEVEL",schema="dbo")

@JsonIdentityInfo(generator=ObjectIdGenerators.PropertyGenerator.class, property="levelId",resolver = DedupingObjectIdResolver.class)
public class RmtLevel implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long levelId;
	private String Description;
	private Set<RmtIntwUsers> rmtIntwUsers = new HashSet<RmtIntwUsers>();
	private Set<RmtIntwQuestions>rmtIntwQuestions=new HashSet<RmtIntwQuestions>();

	public RmtLevel() {
	}
	
	
	public RmtLevel(Long levelId) {
		super();
		this.levelId = levelId;
		
	}


	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@javax.persistence.Id
	@Column(name="ID")
	public Long getLevelId() {
		return levelId;
	}


	public void setLevelId(Long levelId) {
		this.levelId = levelId;
	}

	


	
	
	@Column(name="DESCRIPTION")
	public String getDescription() {
		return Description;
	}



	public void setDescription(String description) {
		Description = description;
	}
	
	@JsonManagedReference("users")
	@OneToMany(fetch = FetchType.LAZY)
	@JoinColumn(name="LEVEL_ID" )
	public Set<RmtIntwUsers> getRmtIntwUsers() {
		return rmtIntwUsers;
	}


	public void setRmtIntwUsers(Set<RmtIntwUsers> rmtIntwUsers) {
		this.rmtIntwUsers = rmtIntwUsers;
	}

	
	@JsonManagedReference("questions") @OneToMany(fetch = FetchType.LAZY) @JoinColumn(name="QLEVEL_ID" )
	public Set<RmtIntwQuestions> getRmtIntwQuestions() {
		return rmtIntwQuestions;
	}


	public void setRmtIntwQuestions(Set<RmtIntwQuestions> rmtIntwQuestions) {
		this.rmtIntwQuestions = rmtIntwQuestions;
	}
	

}
